local L = LibStub("AceLocale-3.0"):NewLocale("LookingForGroup", "enUS", true)

L["Armory"] = true
L["Auto"] = true
L["auto_report"] = "Auto Report"
L["auto_report_desc"] = "Automatically report spamming groups in LFG system"
L["background_search"] = "Background Search"
L["cr_realm_rand_hop"] = "Random Hop"
L["cr_realm_rand_hop_desc"] = [=[Hop to a random realm. Ctrl/Shift + Right-click minimap icon would also do this.
Macro: /lfg cr rand_hop
]=]
L["cr_realm_scan"] = "Scan Your Realm"
L["cr_realm_scan_desc"] = "Scanning your current realm. Right-click minimap icon would also do this."
L["cr_scanningyourcurrentrealm"] = "Scanning Your Current Realm..."
L["Cross Realm"] = true
L["find_f_advanced_2xfilters"] = "Filter keywords after searching. This toggle will be automatically selected if needed."
L["find_f_advanced_class"] = "Groups have >= 2 your class"
L["find_f_advanced_complete"] = "Groups nearly finished grouping"
L["find_f_advanced_gold"] = "WTS/RMT Groups Searching"
L["find_f_advanced_language"] = "Only display certain languages you want. You can select languages in [%s-%s]."
L["find_f_advanced_role"] = "According to your role. For example, if you are a healer, you will not see dungeon groups with a healer in the search results."
L["find_f_encounters"] = [=[Normal Click = This boss must be defeated
Dark Click = This boss must not be defeated
No Click = Do not care whether this boss is defeated or not.]=]
L["find_recommended_desc"] = [=[Normal Click = Display recommended activities only
Dark Click = Display other activities
No Click = Display all activities]=]
L["Keywords"] = true
L["Maximum length"] = true
L["options"] = "Toggles of sub-addons"
L["options_addons"] = "Creating groups using other LFG AddOns' format."
L["options_advanced_hardware"] = "Make LFG running under protected mode. Automatically enabled if needed."
L["options_auto_pve_desc"] = [=[Normal Click = Only join groups with the keyword 'PVE'
Dark Click = Only join groups with the keyword 'PVP'
No click = Disable
|c00ff0000Warning! This option is not guaranteed to work! It'll group you with pvp servers without telling you where you're going even if this option is used.|r]=]
L["options_window"] = "Window Size"
L["Relist"] = true
L["Repeat"] = true
L["Results"] = true
L["rf_mode_desc"] = [=[Normal Click = Realms Blacklist
Dark Click = Realms Whitelist
No click = Disable]=]
L["warning"] = "This information is generated by 3rd-party addons and easily faked. There is no reason to trust it."

