local LSM = LibStub('LibSharedMedia-3.0')

LSM:Register('statusbar', 'Asphyxia', [[Interface\AddOns\EuiScript\textures\StatusBars\Asphyxia]])
LSM:Register('statusbar', 'Bezo', [[Interface\AddOns\EuiScript\textures\StatusBars\Bezo]])
LSM:Register('statusbar', 'Dajova', [[Interface\AddOns\EuiScript\textures\StatusBars\Dajova]])
LSM:Register('statusbar', 'Duffed', [[Interface\AddOns\EuiScript\textures\StatusBars\Duffed]])
LSM:Register('statusbar', 'Flatt', [[Interface\AddOns\EuiScript\textures\StatusBars\Flatt]])
LSM:Register('statusbar', 'Sinaris', [[Interface\AddOns\EuiScript\textures\StatusBars\Sinaris]])
LSM:Register('statusbar', 'Slate', [[Interface\AddOns\EuiScript\textures\StatusBars\Slate]])
LSM:Register('statusbar', 'Smooth', [[Interface\AddOns\EuiScript\textures\StatusBars\Smooth]])
LSM:Register('statusbar', 'Tukui', [[Interface\AddOns\EuiScript\textures\StatusBars\Tukui]])
LSM:Register('statusbar', 'XPerl_1', [[Interface\AddOns\EuiScript\textures\StatusBars\XPerl_StatusBar]])
LSM:Register('statusbar', 'XPerl_2', [[Interface\AddOns\EuiScript\textures\StatusBars\XPerl_StatusBar2]])
LSM:Register('statusbar', 'XPerl_3', [[Interface\AddOns\EuiScript\textures\StatusBars\XPerl_StatusBar3]])
LSM:Register('statusbar', 'XPerl_4', [[Interface\AddOns\EuiScript\textures\StatusBars\XPerl_StatusBar4]])
LSM:Register('statusbar', 'XPerl_5', [[Interface\AddOns\EuiScript\textures\StatusBars\XPerl_StatusBar5]])
LSM:Register('statusbar', 'XPerl_6', [[Interface\AddOns\EuiScript\textures\StatusBars\XPerl_StatusBar6]])
LSM:Register('statusbar', 'XPerl_7', [[Interface\AddOns\EuiScript\textures\StatusBars\XPerl_StatusBar7]])
LSM:Register('statusbar', 'XPerl_8', [[Interface\AddOns\EuiScript\textures\StatusBars\XPerl_StatusBar8]])
LSM:Register('statusbar', 'XPerl_9', [[Interface\AddOns\EuiScript\textures\StatusBars\XPerl_StatusBar9]])
LSM:Register('statusbar', 'XPerl_10', [[Interface\AddOns\EuiScript\textures\StatusBars\XPerl_StatusBar10]])

LSM:Register('statusbar', 'Aluminium Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Aluminium]])
LSM:Register('statusbar', 'Asphyxia Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Asphyxia]])
LSM:Register('statusbar', 'BantoBar Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\BantoBar]])
LSM:Register('statusbar', 'Button Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Button]])
LSM:Register('statusbar', 'Cloud Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Cloud]])
LSM:Register('statusbar', 'Comet Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Comet]])
LSM:Register('statusbar', 'Dabs Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Dabs]])
LSM:Register('statusbar', 'ElvUI Gloss Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\ElvUI]])
LSM:Register('statusbar', 'Falumn Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Falumn]])
LSM:Register('statusbar', 'Flat Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Flat]])
LSM:Register('statusbar', 'Frost Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Frost]])
LSM:Register('statusbar', 'Glamour Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Glamour]])
LSM:Register('statusbar', 'Glamour2 Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Glamour2]])
LSM:Register('statusbar', 'Glamour3 Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Glamour3]])
LSM:Register('statusbar', 'Glamour4 Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Glamour4]])
LSM:Register('statusbar', 'Glamour5 Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Glamour5]])
LSM:Register('statusbar', 'Glamour6 Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Glamour6]])
LSM:Register('statusbar', 'Glamour7 Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Glamour7]])
LSM:Register('statusbar', 'Glaze Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Glaze]])
LSM:Register('statusbar', 'Glaze2 Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Glaze2]])
LSM:Register('statusbar', 'Gloss Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Gloss]])
LSM:Register('statusbar', 'Healbot Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Healbot]])
LSM:Register('statusbar', 'LiteStep Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\LiteStep]])
LSM:Register('statusbar', 'Lyfe Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Lyfe]])
LSM:Register('statusbar', 'Minimalist Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Minimalist]])
LSM:Register('statusbar', 'Otravi Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Otravi]])
LSM:Register('statusbar', 'Outline Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Outline]])
LSM:Register('statusbar', 'Perl Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Perl]])
LSM:Register('statusbar', 'Rocks Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Rocks]])
LSM:Register('statusbar', 'Round Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Round]])
LSM:Register('statusbar', 'Ruben Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Ruben]])
LSM:Register('statusbar', 'Runes Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Runes]])
LSM:Register('statusbar', 'Sinaris Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Sinaris]])
LSM:Register('statusbar', 'Slate Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Slate]])
LSM:Register('statusbar', 'Smooth Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Smooth]])
LSM:Register('statusbar', 'Tukui Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Tukui]])
LSM:Register('statusbar', 'Water Vertical', [[Interface\AddOns\EuiScript\textures\StatusBars\Vertical\Water]])