local T, C, L, G = unpack(select(2, ...))

L["请先加入团队"]             = "Join a raid group before check version."
L["通用"]					  = "General"
L["锚点"]                     = "Anchor"
L["锚点框体"] 				  = "Anchor Frame"
L["选中的框体"]               = "Select Frame"
L["进入战斗锁定"]             = "Entered combat, lock all frames."
L["重置位置"]                 = "Reset Positions"
L["重置位置确认"] 			  = "Do you want to reset all the positions?"
L["重置所有设置"]             = "Reset"
L["重置所有设置确认"] 		  = "Do you want to reset all the settings?"
L["解锁框体"]				  = "Unlock"
L["锁定框体"]				  = "Lock"
L["中间"] 		     		  = "Center"
L["左"] 		     		  = "Left"
L["右"] 		     		  = "Right"
L["上"] 		     		  = "Top"
L["下"] 		     		  = "Bottom"
L["左上"] 		     		  = "Topleft"
L["右上"] 		     		  = "Topright"
L["左下"] 		     		  = "Bottomleft"
L["右下"] 		     		  = "Bottomright"
L["测试"]					  = "Test"
L["禁用插件"]				  = "Disable"
L["静音"]					  = "Mute"
L["不发送聊天讯息"]			  = "Don't sent chat massages"
L["共享配置"]				  = "Share settings"
L["脱战共享"] 				  = "Please sharing when out of combat."
L["入团共享"]				  = "Please sharing in a raid group."
L["已共享"]					  = "Successful shared"
L["导入确认"] 				  = "Do you want to import %s settings from %s?"
L["制作"]					  = "Credits"
L["制作文本"]				  = "|cffEE3A8CAntorus Raid Mods|r\nby Paopao\n\nSpecial thanks for KeaHoarl."

L["图标提示"]				  = "Icon alert"
L["图标大小"] 				  = "Icon size"
L["图标间距"]				  = "Icon gap"
L["排列方向"]                 = "Icon grow direction"
L["大字体大小"]				  = "Fontsize big"
L["小字体大小"]				  = "Fontsize small"
L["启用"] 					  = "Enable"
L["发光"] 					  = "Glow"

L["醒目文字提示"]     		  = "Big alert text"

L["血量提示"]				  = "Boss HP alert"
L["能量提示"]				  = "Boss PP alert"
L["字体大小"]				  = "Fontsize"
L["闪烁"]					  = "Flash"
L["能量"]                     = "Energy"
L["团队高亮图标"]			  = "Highlight icons on raidframes"
L["显示高亮图标"]			  = "Show HL icons for %s"
L["图标透明度"] 			  = "Icon alpha"
L["不显示数字"]               = "Hide cooldown text"

L["分组分担提示"] 			  = "Damage sharing alert"
L["显示分担指示器"]			  = "Show damage sharing alert for %s"
L["你"]						  = "|cffFF0000You!|r"
L["添加喊话"]                 = "Sent msg for %s"

L["声音提示"]				  = "Sound alert"
L["其它"]					  = "Others"
L["点你"]					  = "On you"
L["接圈"]                     = "Soak"
L["靠边"]                     = "Go out"
L["减伤"]                     = "Defend"
L["分散"]					  = "Spread"
L["分担"]					  = "Share Damage"
L["快走开"]					  = "Move"
L["限时"]					  = "Time limit"
L["躲避"]					  = "Avoid"
L["施法"]					  = "Casting"
L["远离"]					  = "Move far away"
L["刷血"]                     = "Massive aoe"
L["出人群"]					  = "Go out"
L["免疫打断"]				  = "Immune interrupt"
L["阶段转换"]        		  = "Phrase change"
L["保持分散"]				  = "Keep spread"
L["注意分担"]				  = "Soak"
L["准备暗影突袭"]             = "Shadow Strike incoming"
L["准备连击"]  				  = "Taeshalach Technique incoming"
L["生命能量"]				  = "Life energy"

L["提示框"]					  = "%s alert"
L["技能提示"]                 = "Boss Mod"

L["姓名板图标"]				  = "Nameplate icons"
L["垂直距离"]			      = "Vertical distance"
L["显示姓名板图标"]           = "Show %s on plates"
L["显示姓名板能量图标"]       = "Show energy on plates for %s"

L["尺寸"]                     = "Scale"
L["无人"]					  = "|cffFF0000None!|r"

L["毁灭者"]	             	  = "|cffADFF2FDestructor|r"
L["净化者"]	             	  = "|cffFF0000Purifier|r"
L["干扰器"]	             	  = "|cffBF3EFFObfuscator|r"
L["恶魔卫士"]                 = "Felguard" 
L["恶魔犬"]                   = "Fel Hound"  
L["邪能领主"]                 = "Fel Lord"
L["科拉佩特隆"]               = "Kerapteron"
L["上船安排"]				  = "Ship arrangement"
L["上船"]					  = "%d on board"

L["屠戮者"]	             	  = "|cffFF8C00Decimator|r"
L["歼灭者"]	             	  = "|cffADFF2FAnnihilator|r"
L["破坏者"]	             	  = "|cff9A32CDDemolisher|r"

L["余烬数量"]			 	  = "|cffEE7600Ember|r %d |cff999999Sleep|r %d "
L["余烬"]                     = "Ember"
L["烈焰撕裂分担提示"]		  = "Flame Rend arrangement"
L["易伤"]				 	  = "Vulnerabilities"

L["灵魂凋零计数"]			  = "Soulblight index"
L["护送提醒"]				  = "Convoy alert"
L["需要护送"]				  = "Need convoy"
L["萨格拉斯的凝视"]			  = "Sargeras' Gaze"
L["朋友圈"]					  = "Sock"
L["孤儿圈"]					  = "Move out"
L["萨格拉斯的判决"]			  = "Sentence of Sargeras"
L["锁链"]					  = "Sentence"
L["树能量"]					  = "|cff66CD00Tree Energy %d|r"
L["树生命灰"]				  = "|cffD9D9D9Tree HP %d%|r"
L["树生命红"] 				  = "|cffCD5555Tree HP %d%|r"
L["树死亡"]					  = "|cffD9D9D9Tree Dead|r"
L["卡兹格罗斯能量"]			  = "|cff66CDAATitanforged %d|r"
L["阿古斯P2"]				  = "Let the fury of the sea wash away this corruption!"
L["阿古斯重要点名监视"]		  = "Important debuff bars."